apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ec-node-hello-d4m7
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ec-node-hello-d4m7
    app.kubernetes.io/part-of: ec-node-hello
  name: ec-node-hello-d4m7
  namespace: bsutter-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: ec-node-hello-d4m7
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: ec-node-hello-d4m7
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:7849644eba2b5d8502017c4767b7a6c830758455771c7753528908741a1892fe
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
