apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ec-node-hello-d4m7
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ec-node-hello-d4m7
    app.kubernetes.io/part-of: ec-node-hello
  name: ec-node-hello-d4m7
  namespace: bsutter-tenant
spec:
  path: /
  port:
    targetPort: 3001
  to:
    kind: Service
    name: ec-node-hello-d4m7
    weight: null
status: {}
