apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ec-node-hello-d4m7
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ec-node-hello-d4m7
    app.kubernetes.io/part-of: ec-node-hello
  name: ec-node-hello-d4m7
  namespace: bsutter-tenant
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: ec-node-hello-d4m7
status:
  loadBalancer: {}
